/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VirtualizationInfo {
  arch: string
  os: string
  cpuSupported: boolean
  cpuFeatureName: string
  osReportedEnabled: boolean
  osCheckDetails: string
  overallStatusMessage: string
}
export declare function getVirtualization(): VirtualizationInfo
